### ISSUE TITLE
Add-on approval on hold

### ISSUE THREAD

**Issue by jobisoft** [kgraefe/thunderbird-no-tag-colors#4]
Hi,

you should have received a message from the Mozilla add-on review process. I have not received feedback yet and the approval of your add-on is on hold. Could you check your messages? You can reach out to me directly (john at thunderbird.net).

**Comment by jobisoft** [comment]
Uups. I should have read the other issues first. So you got the message and are aware.

**Comment by kgraefe** [comment]
Thanks for reaching out. Since I'm doing this on my spare time it can take quite some time until both issues will be resolved.
